pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stor.urls'))
]

stor/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('add-drug', views.add_drug, name='add_drug'),
    path('Drug-Request/<int:pk>', views.DrugRequest, name='DrugRequest'),
    path('drug-exist/<str:pk>', views.check_drug, name='check_drug'),
    path('pharma', views.pharma, name = 'pharma'),
    path('done/<str:drug_name>/<int:pk>', views.sell_drug, name='sell_drug'),
    path('finish/<int:pk>', views.delete_temp, name = 'delete_temp'),
    path('patients-doctor', views.doctor_patients, name="doctor_patients"),
    path('history-patients/<int:pk>', views.HistoryPatient, name = 'HistoryPatient'),
    path('drug-for-patient/<int:pk>', views.drug_for_patient, name = 'drug_for_patient'),
    path('labform/<int:pk>', views.labRequest, name='labform'),
    path('labratory/', views.labratory, name='labratory'),
    path('labratory-to-dr/<int:pk>', views.labratoryToDr, name='labratory-to-dr'),
    path('labratory-result/<int:pk>', views.LabratoryResult, name='labratory-result')



]

stor/models.py
from django.db import models
# Create your models here.
sex = (
    ("Male","M"),
    ("Female","F"),
)

class Drug_Stor(models.Model):
    name_drug = models.CharField(max_length=100, default=None)
    quantity_drugs = models.IntegerField(default= 0)
    price_per_drug = models.IntegerField(default= 0)
    descriptions_drug = models.TextField(max_length=1000)
    def __str__(self):
            return self.name_drug
class Register_Patient(models.Model):
    """Model definition for Register_Patient."""

    First_Name = models.CharField(max_length=50)
    Middle_Name = models.CharField(max_length=50)
    Last_Name = models.CharField(max_length=50)
    full_name = models.CharField(max_length=100, default="")
    Age = models.IntegerField(default=0)
    Sex = models.CharField(max_length=10,choices=sex)
    Address = models.CharField(max_length=100)
    Phone_Number = models.CharField(max_length=15)
    Emergency_Phone_Number = models.CharField(max_length=15)
    Created_at = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for Register_Patient."""

        verbose_name = 'Register_Patient'
        verbose_name_plural = 'Register_Patients'

    class Meta:
        ordering = ['Created_at']
        
    def __str__(self):
        """Unicode representation of Register_Patient."""
        name = self.First_Name + ' ' + self.Middle_Name + ' ' + self.Last_Name
        return name
class drug_request (models.Model):
      patient = models.ForeignKey(Register_Patient, on_delete=models.CASCADE, default=None)
      requested_at = models.DateTimeField(auto_now = True)
      drug_name = models.CharField(max_length=100)
      def __str__(self):
             return self.patient.First_Name
class History_patient(models.Model):
    patient = models.ForeignKey(Register_Patient, on_delete=models.CASCADE, default=None)
    hisory_text = models.TextField(max_length=100000000)
    def __str__(self) -> str:
          return self.patient.First_Name
class Doctor(models.Model):
     patient = models.ForeignKey(Register_Patient, on_delete=models.CASCADE, default=None)
     patient_history = models.ForeignKey(History_patient, models.CASCADE, default=None)
     First_name_Dr = models.CharField(max_length=50)
     Last_name_Dr = models.CharField(max_length=50)
     time_with_patient = models.DateTimeField(auto_now=True)
     def __str__(self):
           return self.patient.First_Name
class LabTestName(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class LabTest(models.Model):
    lab_tase_name = models.ForeignKey(LabTestName, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class User_lab_temporary(models.Model):
    Patient_name = models.ForeignKey(Register_Patient, on_delete=models.PROTECT)
    # patient_name = models.CharField(max_length=100, blank=True)
    labs = models.CharField(max_length=1000, blank=True)

    # test_name = models.ForeignKey(LabTestName, on_delete=models.CASCADE)
    
    # print(labs)
    def save_selected_labs(self, selected_labs):
        labs_str = ",".join(selected_labs)
        self.labs = labs_str
        self.save()

    def get_selected_labs(self):
        return self.labs.split(",") if self.labs else []


    def __str__(self) -> str:
        return f"{self.id} {self.Patient_name} "

class LabResult(models.Model):
     patient_name = models.ForeignKey(User_lab_temporary, on_delete=models.PROTECT)

     resulut = models.CharField(max_length=1000)
     

    
      

templates/add_drug.html
{%load static%}
<link rel="stylesheet" href="{%static 'tables.css'%}">
<a href="/pharma"><Button><-</Button></a>
<h1>

    Add Drug
	
</h1>
<div>
    <form method="POST" action="">
        {% csrf_token %}
        <h3>
            {{form.as_p}}
        </h3>
        <input type="Submit" value="Submit" name="submit"/>
    </form>
	{%if all_drug%}
	<table>
		<th>
			<!-- <td>Order</td> -->
			<td>Name of drug</td>
			<td>Quantity of drug</td>
			<td>Price of per one drug</td>
			<td>Discribtions</td>
		</th>
		{%for all_drug in all_drug%}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{all_drug.name_drug}}</td>
			<td>{{all_drug.quantity_drugs}}</td>
			<td>{{all_drug.price_per_drug}}</td>
			<td>{{all_drug.descriptions_drug}}</td>
		</tr>
		{%endfor%}
	</table>
	{%endif%}
</div>

templates/checkDrug.html
<html>
	<head>Drug Store</head>
	<body>
		{%if patient_drug%}
		<p>{{patient_drug.name_drug}}</p>
		<p>Price : {{patient_drug.price_per_drug}}</p>
		<p>Descriptions : {{patient_drug.descriptions_drug}}</p>
		{%else%}
		<p>their is no drug in the stor</p>
		{%endif%}
		<form action="", method="POST">
			{%csrf_token%}
			<input type="submit" value="Back">
		</form>
	</body>
</html>

templates/drug_for_patient.html
{%load static%}
<html>
	<link rel="stylesheet" href="{%static 'tables.css'%}">
	
	<head>Today list of Drug for patient</head>

	<body>
		<table>
			{%if DrugPatient%}
			<th>
				<!-- <td>Order</td> -->
				<td>Name</td>
				<td>Phone number</td>
				<td>sex</td>
				<td>Drug</td>
				<td>Check</td>
				<td>Status</td>
			</th>
			{%for DrugPatient in DrugPatient%}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>{{DrugPatient.patient.full_name}}</td>
				<td>{{DrugPatient.patient.Phone_Number}}</td>
				<td>{{DrugPatient.patient.Sex}}</td>
				<td>{{DrugPatient.drug_name}}</td>
				<td><a href="/drug-exist/{{DrugPatient.drug_name}}"><button>Check</button></a></td>
				<td><a href="/done/{{DrugPatient.drug_name}}/{{DrugPatient.id}}"><button>Done</button></td>
			</tr>
			{%endfor%}
			{%else%}
			<h1>No Data</h1>
			{%endif%}
		</table>
		<br><br>
		<form action="" method="POST">
			{%csrf_token%}
			<input type="submit" value="Bakc">
		</form>
	</body>
</html>

templates/drug_request.html
<h1>
    Add Drug
	
</h1>
<div>
    <form method="POST" action="">
        {% csrf_token %}
        <h3>
			Patient Name : {{patient.First_Name}} {{patient.Middle_Name}} {{patient.Last_Name}}
            {{form.as_p}}
        </h3>
        <input type="Submit" value="Submit" name="submit"/>
    </form>
</div>
</div>
	<a href="/add-drug"><button>Add drug</button></a>
</html>

templates/history_patient.html
<html>
	<head>History Patient</head>
	<body>
		<h3>
			Name : {{history.patient.First_Name}} {{history.patient.Middle_name}} {{history.patient.Last_name}} <br>
			Sex : {{histry.patient.Sex}} <br>
			Age : {{history.patient.Age}} <br>
			Phone Number : {{history.patient.Phone_Number}} <br>
			Emergency Phone Number : {{history.patient.Emergency_Phone_Number}} <br>
		</h3>
		<h1>Previes History</h1>
		<h4>
			{{historyText}}
		</h4>

		<h3>New History</h3>

		<form method="POST" action="">
			{% csrf_token %}
			<textarea name="text_history" cols="30" rows="10" placeholder="History"></textarea>
			<br><br>
			<input type="Submit" value="Submit" name="submit"/>
		</form>
		<a href="/labform/{{history.patient.id }}"><button>Labratory Form</button></a><br><br>
		<a href="/labratory-result/{{history.patient.id }}"><button>View Labratory Result</button></a><br><br>
		<a href="/Drug-Request/{{history.patient.id}}"><button>Pharmacy</button></a>
	</body>
</html>

templates/lab_request_form.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lab Request Form</title>
</head>
<body>
    <h1>LAB REQUEST FORM</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for section in sections %}
            <h3>{{ section.name }}</h3>
            {% for labtest in section.labtest_set.all %}
                <label>
                    <input type="checkbox" name="selected_labs" value="{{ labtest.name }}">
                    {{ labtest.name }}
                </label><br>
            {% endfor %}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>
   
</body>
</html> 
 


  <!-- your_template.html -->

<!-- <!DOCTYPE html>
<html>
<head>
    <title>Save User Lab Temporary</title>
</head>
<body>
    <h1>Save User Lab Temporary</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html> -->

templates/labratory.html
{%load static%}
<html>
	<link rel="stylesheet" href="{%static 'tables.css'%}">
	
	<head>Today list of patients</head>

	<body>
		{%if data%}
		<table>
			<th>
				<!-- <td>Order</td> -->
				<td>Name</td>
				
				<td>Test</td>
				<td>Status</td>
			</th>
			{%for data in data%}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>{{data.Patient_name}}</td>
				<td><a href="/labratory-to-dr/{{ forloop.counter }}"><button>View</button></td>
				<td><a href="/finish/{{patients_DR.id}}"><button>Done</button></td>
			</tr>

           
			{%endfor%}
            
		</table>
        
		{%else%}
		<h1>There is no patient for today</h1>
		{%endif%}

        <p>{{data.data.id}}</p>
	</body>
</html>

templates/labratory_result.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Labratory Result</title>
</head>
<body>

    <h1>{{ user.patient_name }}</h1>

   
        <p>{{ user.result }}</p>
    
</body>
</html>

templates/labratory_to_doctor.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Labratory To Doctor</title>
</head>
<body>
    <h1>Labratory to Doctor</h1>
	<h1>Patient Name : {{ user.Patient_name }}</h1>
    <p>lab Test Type : {{ user.labs }}</p>

	<form method="POST" action="">
		{% csrf_token %}
		<textarea name="result" cols="30" rows="10" placeholder="Result"></textarea>
		<br><br>
		<input type="Submit" value="Submit" name="submit"/>
	</form>
</body>
</html>

templates/patient_for_dr.html
{%load static%}
<html>
	<link rel="stylesheet" href="{%static 'tables.css'%}">
	
	<head>Today list of patients</head>

	<body>
		{%if patients_DR%}
		<table>
			<th>
				<!-- <td>Order</td> -->
				<td>Name</td>
				<td>Phone number</td>
				<td>sex</td>
				<td>History</td>
				<td>Status</td>
			</th>
			{%for patients_DR in patients_DR%}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>{{patients_DR.patient.First_Name}}</td>
				<td>{{patients_DR.patient.Phone_Number}}</td>
				<td>{{patients_DR.patient.Sex}}</td>
				<td><a href="history-patients/{{patients_DR.patient.id}}"><button>View</button></td>
				<td><a href="/finish/{{patients_DR.id}}"><button>Done</button></td>
			</tr>
			{%endfor%}
		</table>
		{%else%}
		<h1>There is no patient for today</h1>
		{%endif%}
	</body>
</html>

templates/pharma.html
{%load static%}
<html>
	<a href="/add-drug"><button>Add Drug</button></a><br><br><br>
	<link rel="stylesheet" href="{%static 'tables.css'%}">
	<head>Pharma</head>
	<body>
		<form action="" method="GET">
			<p>Patient Name</p>
			<p><input type="text" name="search"></p>
			<input type="submit" value="Search">
		</form>
		<div>
			{%if patients%}
			<table>
				<thead>
					<td>Name</td>
					<td>Phone Number</td>
					<td>View</td>
				</thhead>
				{% for patient in patients %}
				<tr>
					<td>{{patient.full_name}}</td>
					<td>{{patient.Phone_Number}}</td>
					<td><a href="drug-for-patient/{{patient.id}}"><button>View</button></a></td>
				</tr>
				{% endfor %}
			</table>
			{%endif%}
		</div>
	</body>
</html>